//
// Created by rostik on 10/20/22.
//


#ifndef LEXER_H
#define LEXER_H

#include <stdio.h>
#include "token.h"

//LEXEMY
enum T_STATE {
    ST_START,
    ST_VAR_PREFIX,
    ST_VAR,
    ST_OP_ASSIGN,
    ST_OP_PLUS,
    ST_OP_MINUS,
    ST_OP_DIVIDE,
    ST_OP_MULTIPLY,
    ST_OP_CONCAT,
    ST_OP_LESSER_THAN,
    ST_OP_GREATER_THAN,
    //TBD
    ST_FUNC,
    ST_ERROR,
    ST_INT_LITERAL,
    ST_DOUBLE_LITERAL,
    ST_STRING_LITERAL,
    ST_LEFT_PARENTHESES,
    ST_RIGHT_PARENTHESES,
    ST_LEFT_CURLYBRACKET,
    ST_RIGHT_CURLYBRACKET,
    ST_DATA_TYPE,
    ST_COMMA,
    ST_KEYWORD_FLOAT,
    ST_KEYWORD_STRING,
    ST_KEYWORD_INT,
    ST_KEYWORD_COLON,
    ST_KEYWORD_ELSE,
    ST_KEYWORD_IF,
    ST_KEYWORD_WHILE,
    ST_KEYWORD_RETURN,
    ST_KEYWORD_NULL,
    ST_KEYWORD_VOID,
};

TOKEN_T * get_next_token();

#endif